<?php

$search[1]='<td width="115"><form method="get" action="http://www.amazon.com/exec/obidos/external-search" target="_blank"><font size="1">Amazon.com</font><br><input type="text" name="keyword" size="5" onFocus="this.select()"><input type="hidden" name="mode" value="blended"><input type="hidden" name="tag" value="bookmarkmanag-20"><input type="submit" value="Go"></td></form>';

$search[2]='<td width="115"><form method="get" action="http://www.amazon.co.uk/exec/obidos/external-search" target="_blank"><font size="1">Amazon.co.uk</font><br><input type="text" name="keyword" size="5" onFocus="this.select()"><input type="hidden" name="mode" value="blended"><input type="hidden" name="tag" value="bookmarkmanag-21"><input type="submit" value="Go"></td></form>';

$search[3]='<td width="115"><form method="get" action="http://www.amazon.de/exec/obidos/external-search" target="_blank"><font size="1">Amazon.de</font><br><input type="text" name="keyword" size="5" onFocus="this.select()"><input type="hidden" name="mode" value="blended"><input type="hidden" name="tag" value="freizeitagenturd"><input type="hidden" name="tag-id" value="freizeitagenturd"><input type="submit" value="Go"></td></form>';

$search[4]='<td width="115"><form method="get" action="http://www.amazon.fr/exec/obidos/external-search" target="_blank"><font size="1">Amazon.fr</font><br><input type="text" name="keyword" size="5" onFocus="this.select()"><input type="hidden" name="mode" value="blended"><input type="hidden" name="tag" value="bso-21"><input type="submit" value="Go"></td></form>';

$search[5]='<td width="115"><form method="get" action="http://www.amazon.co.jp/exec/obidos/external-search" target="_blank"><font size="1">Amazon.co.jp</font><br><input type="text" name="keyword" size="5" onFocus="this.select()"><input type="hidden" name="mode" value="blended"><input type="hidden" name="tag" value="bookmarkmanag-21"><input type="submit" value="Go"></td></form>';

$search[6]='<td width="115"><form method="get" action="http://www.amazon.ca/exec/obidos/external-search" target="_blank"><font size="1">Amazon.ca</font><br><input type="text" name="keyword" size="5" onFocus="this.select()"><input type="hidden" name="mode" value="blended"><input type="hidden" name="tag" value="organizer0a-20"><input type="submit" value="Go"></td></form>';

$search[7]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="usa"><font size="1">eBay.com</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[8]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="uk"><font size="1">eBay.co.uk</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[9]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="fr"><font size="1">eBay.fr</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[10]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="au"><font size="1">eBay.com.au</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[11]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="in"><font size="1">eBay.in</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[12]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="ca"><font size="1">eBay.ca</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[13]='<td width="115"><form name="dict" method="post" action="http://www.imdb.com/Find" target="_blank"><a href="http://www.imdb.com/" target="_blank"><font size="1">IMDB</font></a><br><input name="for" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[14]='<td width="115"><form name="dict" method="post" action="http://uk.imdb.com/Find" target="_blank"><a href="http://uk.imdb.com/" target="_blank"><font size="1">IMDB</font></a><br><input name="for" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[15]='<td width="115"><form name="dict" method="post" action="http://german.imdb.com/Find" target="_blank"><a href="http://german.imdb.com/" target="_blank"><font size="1">IMDB</font></a><br><input name="for" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[16]='<td width="115"><form name="dict" method="post" action="http://french.imdb.com/Find" target="_blank"><a href="http://french.imdb.com/" target="_blank"><font size="1">IMDB</font></a><br><input name="for" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[17]='<td width="115"><form name="dict" method="post" action="http://spanish.imdb.com/Find" target="_blank"><a href="http://spanish.imdb.com/" target="_blank"><font size="1">IMDB</font></a><br><input name="for" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[18]='<td width="115"><form method="get" action="http://en.wiktionary.org/wiki/" target="_blank"><a href="http://en.wiktionary.org/" target="_blank"><font size="1">Wiktionary</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[19]='<td width="115"><form name="dict" method="post" action="http://www.m-w.com/cgi-bin/dictionary" target="_blank"><a href="http://www.m-w.com/" target="_blank"><font size="1">M-W</font></a><br><input type="hidden" name="book" value="Dictionary"><input name="va" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[20]='<td width="115"><form name="search" class="inline" method="get" action="http://en.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://en.wikipedia.org/" target="_blank"><font size="1">Wikipedia (en)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[21]='<td width="115"><form name="search" class="inline" method="get" action="http://de.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://de.wikipedia.org/" target="_blank"><font size="1">Wikipedia (de)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[22]='<td width="115"><form action="search-all.php" method="post" target="main"><font size="1">Organizer</font><br><input type="text" name="text_search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[23]='<td width="115"><form method="get" action="http://www.google.com/custom" target="google_window"><font size="1">Google.com</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[24]='<td width="115"><form method="get" action="http://www.google.co.uk/custom" target="google_window"><font size="1">Google.co.uk</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[25]='<td width="115"><form method="get" action="http://www.google.de/custom" target="google_window"><font size="1">Google.de</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input><input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="de"></input></td></form>';

$search[26]='<td width="115"><form method="get" action="http://www.google.nl/custom" target="google_window"><font size="1">Google.nl</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="nl"></input></td></form>';

$search[27]='<td width="115"><form method="get" action="http://www.google.es/custom" target="google_window"><font size="1">Google.es</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="es"></input></td></form>';

$search[28]='<td width="115"><form method="get" action="http://www.google.at/custom" target="google_window"><font size="1">Google.at</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="de"></input></td></form>';

$search[29]='<td width="115"><form method="get" action="http://www.google.ch/custom" target="google_window"><font size="1">Google.ch</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="de"></input></td></form>';

$search[30]='<td width="115"><form method="get" action="http://www.google.ca/custom" target="google_window"><font size="1">Google.ca</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[31]='<td width="115"><form method="get" action="http://www.php.net/search.php" target="_blank"><a href="http://www.php.net/" target="_blank"><font size="1">php.net</font></a><br><input type="hidden" name="show" value="quickref"><input type="text" name="pattern" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

//$search[32]='<td width="115"><form method="get" action="http://www.alltheweb.com/search" target="_blank"><a href="http://www.alltheweb.com/" target="_blank"><font size="1">AlltheWeb</font></a><br><input type="text" name="q" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[33]='<td width="115"><form name="search" class="inline" method="get" action="http://es.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://es.wikipedia.org/" target="_blank"><font size="1">Wikipedia (es)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[34]='<td width="115"><form name="search" class="inline" method="get" action="http://pl.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://pl.wikipedia.org/" target="_blank"><font size="1">Wikipedia (pl)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[35]='<td width="115"><form name="search" class="inline" method="get" action="http://fr.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://fr.wikipedia.org/" target="_blank"><font size="1">Wikipedia (fr)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[36]='<td width="115"><form name="search" class="inline" method="get" action="http://ja.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://ja.wikipedia.org/" target="_blank"><font size="1">Wikipedia (ja)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[37]='<td width="115"><form name="search" class="inline" method="get" action="http://sv.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://sv.wikipedia.org/" target="_blank"><font size="1">Wikipedia (sv)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[38]='<td width="115"><form name="search" class="inline" method="get" action="http://pt.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://pt.wikipedia.org/" target="_blank"><font size="1">Wikipedia (pt)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[39]='<td width="115"><form name="search" class="inline" method="get" action="http://nl.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://nl.wikipedia.org/" target="_blank"><font size="1">Wikipedia (nl)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[40]='<td width="115"><form name="search" class="inline" method="get" action="http://it.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://it.wikipedia.org/" target="_blank"><font size="1">Wikipedia (it)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[41]='<td width="115"><form name="search" class="inline" method="get" action="http://zh.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://zh.wikipedia.org/" target="_blank"><font size="1">Wikipedia (zh)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[42]='<td width="115"><form method="get" action="http://froogle.google.co.uk/froogle" target="google_window"><font size="1">Google Products</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[43]='<td width="115"><form method="get" action="http://froogle.google.com/froogle" target="google_window"><font size="1">Google Products</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[44]='<td width="115"><form method="get" action="http://froogle.google.de/froogle" target="google_window"><font size="1">Google Products</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="de"></input></td></form>';

$search[45]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="nl"><font size="1">eBay.nl</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[46]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="de"><font size="1">eBay.de</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[47]='<td width="115"><form method="get" action="http://www.google.com.au/custom" target="google_window"><font size="1">Google.com.au</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[48]='<td width="115"><form method="get" action="http://www.google.fr/custom" target="google_window"><font size="1">Google.fr</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="fr"></input></td></form>';

$search[49]='<td width="115"><form method="get" action="http://www.google.co.jp/custom" target="google_window"><font size="1">Google.co.jp</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="Shift_JIS"></input><input type="hidden" name="oe" value="Shift_JIS"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="ja"></input></td></form>';

$search[50]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="it"><font size="1">eBay.it</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[51]='<td width="115"><form method="get" action="http://www.google.it/custom" target="google_window"><font size="1">Google.it</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="it"></input></td></form>';

$search[52]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="ch"><font size="1">eBay.ch</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[53]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="at"><font size="1">eBay.at</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[54]='<td width="115"><form method="get" action="http://www.chinese-course.com/show-words-guest.php" target="_blank"><a href="http://www.chinese-course.com/" target="_blank"><font size="1">Chinese Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[55]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="befr"><font size="1">eBay.be</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[56]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="benl"><font size="1">eBay.be</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[57]='<td width="115"><form method="get" action="http://www.google.ie/custom" target="google_window"><font size="1">Google.ie</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[58]='<td width="115"><form method="get" action="http://www.german-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.german-flashcards.com/" target="_blank"><font size="1">German Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[59]='<td width="115"><form method="get" action="http://www.youtube.com/results" target="_blank"><a href="http://www.youtube.com/" target="_blank"><font size="1">YouTube</font></a><br><input name="search_query" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[60]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="sg"><font size="1">eBay.com.sg</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[61]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="hk"><font size="1">eBay.com.hk</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[62]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="se"><font size="1">Tradera</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[63]='<td width="115"><form method="get" action="http://www.google.co.th/custom" target="google_window"><font size="1">Google.co.th</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="th"></input></td></form>';

$search[64]='<td width="115"><form name="search" class="inline" method="get" action="http://th.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://th.wikipedia.org/" target="_blank"><font size="1">Wikipedia (th)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[65]='<td width="115"><form method="get" action="http://www.google.se/custom" target="google_window"><font size="1">Google.se</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="sv"></input></td></form>';

$search[66]='<td width="115"><form method="get" action="http://www.google.co.in/custom" target="google_window"><font size="1">Google.co.in</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[67]='<td width="115"><form method="get" action="http://www.google.com.hk/custom" target="google_window"><font size="1">Google.com.hk</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="zh-TW"></input></td></form>';

$search[68]='<td width="115"><form method="get" action="http://www.google.com.ar/custom" target="google_window"><font size="1">Google.com.ar</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="es"></input></td></form>';

$search[69]='<td width="115"><form method="get" action="http://www.google.com.tw/custom" target="google_window"><font size="1">Google.com.tw</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="zh-TW"></input></td></form>';

$search[70]='<td width="115"><form method="get" action="http://www.google.co.kr/custom" target="google_window"><font size="1">Google.co.kr</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="ko"></input></td></form>';

$search[71]='<td width="115"><form method="get" action="http://www.google.ru/custom" target="google_window"><font size="1">Google.ru</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="ru"></input></td></form>';

$search[72]='<td width="115"><form method="get" action="http://www.google.com.gr/custom" target="google_window"><font size="1">Google.com.gr</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="el"></input></td></form>';

$search[73]='<td width="115"><form method="get" action="http://www.google.co.il/custom" target="google_window"><font size="1">Google.co.il</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="iw"></input></td></form>';

$search[74]='<td width="115"><form method="get" action="http://www.google.com.sg/custom" target="google_window"><font size="1">Google.com.sg</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-1"></input><input type="hidden" name="oe" value="ISO-8859-1"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="en"></input></td></form>';

$search[75]='<td width="115"><form method="get" action="http://www.google.pl/custom" target="google_window"><font size="1">Google.pl</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-2"></input><input type="hidden" name="oe" value="ISO-8859-2"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="pl"></input></td></form>';

$search[76]='<td width="115"><form name="search" class="inline" method="get" action="http://pl.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://pl.wikipedia.org/" target="_blank"><font size="1">Wikipedia (pl)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[77]='<td width="115"><form method="get" action="http://www.google.ro/custom" target="google_window"><font size="1">Google.ro</font><br><input type="text" name="q" size="5" maxlength="255" value=""></input><input type="submit" name="sa" value="Go"></input>
<input type="hidden" name="client" value="'._GOOGLE_ADSENSE_ID.'"></input><input type="hidden" name="forid" value="1"></input><input type="hidden" name="channel" value="'._GOOGLE_ADSENSE_CHANNEL.'"></input><input type="hidden" name="ie" value="ISO-8859-2"></input><input type="hidden" name="oe" value="ISO-8859-2"></input><input type="hidden" name="cof" value="GALT:#008000;GL:1;DIV:#336699;VLC:663399;AH:center;BGC:FFFFFF;LBGC:336699;ALC:0000FF;LC:0000FF;T:000000;GFNT:0000FF;GIMP:0000FF;FORID:1"></input><input type="hidden" name="hl" value="ro"></input></td></form>';

$search[78]='<td width="115"><form name="search" class="inline" method="get" action="http://ro.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://ro.wikipedia.org/" target="_blank"><font size="1">Wikipedia (ro)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[79]='<td width="115"><form method="get" action="http://www.online-spanish-course.com/show-words-guest.php" target="_blank"><a href="http://www.online-spanish-course.com/" target="_blank"><font size="1">Spanish Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[80]='<td width="115"><form name="search" class="inline" method="get" action="http://ru.wikipedia.org/w/wiki.phtml" target="_blank"><a href="http://ru.wikipedia.org/" target="_blank"><font size="1">Wikipedia (ru)</font></a><br><input type=text name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[81]='<td width="115"><form method="get" action="load-ebay.php" target="_blank"><input type="hidden" name="country" value="es"><font size="1">eBay.es</font><br><input name="search_text" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[82]='<td width="115"><form method="get" action="http://www.french-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.french-flashcards.com/" target="_blank"><font size="1">French Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[83]='<td width="115"><form method="get" action="http://www.italian-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.italian-flashcards.com/" target="_blank"><font size="1">Italian Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[84]='<td width="115"><form method="get" action="http://www.portuguese-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.portuguese-flashcards.com/" target="_blank"><font size="1">Portuguese Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[85]='<td width="115"><form method="get" action="http://www.dutch-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.dutch-flashcards.com/" target="_blank"><font size="1">Dutch Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[86]='<td width="115"><form method="get" action="http://www.korean-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.korean-flashcards.com/" target="_blank"><font size="1">Korean Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[87]='<td width="115"><form method="get" action="http://www.swedish-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.swedish-flashcards.com/" target="_blank"><font size="1">Swedish Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[88]='<td width="115"><form method="get" action="http://www.thai-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.thai-flashcards.com/" target="_blank"><font size="1">Thai Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[89]='<td width="115"><form method="get" action="http://www.japanese-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.japanese-flashcards.com/" target="_blank"><font size="1">Japanese Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

$search[90]='<td width="115"><form method="get" action="http://www.russian-flashcards.com/show-words-guest.php" target="_blank"><a href="http://www.russian-flashcards.com/" target="_blank"><font size="1">Russian Dict</font></a><br><input name="search" size="5" onFocus="this.select()"><input type="submit" value="Go"></td></form>';

?>